import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Flashcard App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='w-screen h-screen overflow-hidden flex flex-col justify-center items-center'>
        <h1 className='text-center text-3xl m-10'>Flashcard App</h1>
        <div className='flex w-full flex-col items-center'>
          <Link href="/card/0"><a>
            <button className='w-32 h-20 bg-gray-200 rounded-md'>
              Start
            </button>
          </a></Link>
        </div>
      </main>
    </div>
  )
}

export default Home
